document.writeln('<header>');
document.writeln('<div class="wrap cl">');
document.writeln('<a href="https://file.henan.gov.cn/"><img src="https://file.henan.gov.cn/4500000038/new/img/logoimg.png" class="logoimg fl"></a>');
document.writeln('<div class="headbox fr"><div class="cl"><div class="vxbox fl">');
document.writeln('<a href=""><img src="https://file.henan.gov.cn/4500000038/new/img/vxlogo.png" alt=""></a>');
document.writeln('<a href="">无障碍</a>');
document.writeln('</div>');
document.writeln('<div class="register fr">');
document.writeln('<a href="https://my.henan.gov.cn/login" target="_blank">登录</a>');
document.writeln('<span>|</span>');
document.writeln('<a href="https://my.henan.gov.cn/userprofile/register" target="_blank">注册</a>');
document.writeln('</div></div>');
document.writeln('<form name="search" action="http://search.sgj.henan.gov.cn/jrobot/search.do" method="get" target="_blank">');
document.writeln('<input type="hidden" name="webid" value="10006">');
document.writeln('<input type="hidden" name="pos" value="title">');
document.writeln('<input type="hidden" name="od" value="0">');
document.writeln('<input type="hidden" name="category" value="hnsgj_all">');
document.writeln('<input type="text"  id="inputTxt"  name="q" placeholder="请输入您要找的关键字">');
document.writeln('<input type="submit"  value=""  id="inputBtn">');
document.writeln('</form></div></div></header>');